### ISSUE TITLE
How to reproduce the experimental results in the paper?

### ISSUE THREAD

**Issue by YxRicardo** [yolandalalala/GNNInterpreter#3]
Hello, I want to reproduce the results presented in your paper. I downloaded the datasets from the link and tried the default parameters in the jupyter notebooks but none of them can reproduce the results in your paper. Could you please provide me with the parameters to reproduce the results? I really appreciate that.

**Comment by yolandalalala** [comment]
Thanks for asking! The reason is that, the checkpoints of the GNN classifiers we explained when writing the paper has been lost so we have to train a new GNN classifier to be explained for the code release. Therefore, the code will produce slightly different results than the paper. We are sorry that there is nothing we can do to help you reproduce the exactly same results as the paper.

**Comment by yolandalalala** [comment]
@YxRicardo By the way, if you observe that our code produces completely different results than the paper, please check whether your python environment follows our specified version. For your convenience, I just update the repo's README by making the installation process easier. Please feel free to let us know if you still cannot reproduce similar results as the paper after following the updated instruction for installing the python environment.

**Comment by YxRicardo** [comment]
> @YxRicardo By the way, if you observe that our code produces completely different results than the paper, please check whether your python environment follows our specified version. For your convenience, I just update the repo's README by making the installation process easier. Please feel free to let us know if you still cannot reproduce similar results as the paper after following the updated instruction for installing the python environment.

Thanks a lot for your help and I really appreciate that. I tried to build a new environment from your .yml file, but both of my Windows and Linux computers couldn't pass the conda environment solving. So I created the environment by myself with the versions shown in the readme file (python3.10 + pytorch2.0 + pyg2.3), unfortunately it still didn't work. Here is an example of an explanation of Mutagen in the jupyter notebook with default parameters. 
![Screenshot 2024-03-29 001556](https://github.com/yolandalalala/GNNInterpreter/assets/73523846/2f5962ac-a6e2-4227-89cc-2163c102a3f6)

**Comment by yolandalalala** [comment]
@YxRicardo For the example you've shown above, I wouldn't consider this as "it doesn't work" because the result strictly complies with the definition of an explanation graph where the model predicted probability = 1. If you want a more human-interpretable graph, there are 3 things you might want to try:

1. Adjust the connectivity constraint as follows,
   ```python
   dict(key="theta_pairs", criterion=KLDivergencePenalty(binary=True), weight=0) # try increase this weight
   ```
   As the name suggested, the connectivity constraint will encourage the explanation graph to be more connected. The result you've shown appears scattered because the weight for this term is set to 0 by default. This issue was also discussed in #2.

2. Adjust the `budget` parameter in the `BudgetPenalty` to make the explanation graph larger. The higher the `budget`, the larger the explanation graph you will get.

3. It's also worth mentioning that, for the Mutag dataset, the `EmbeddingCriterion` is especially important because the training data follows very specific patterns as they are all valid molecule structures. The information about these patterns is encoded in the training graph embeddings, which makes applying `EmbeddingCriterion` essential for generating explanation graphs that resemble the real data.

For more details about how to tune the parameters, please refer to our paper: https://openreview.net/forum?id=rqq6Dh8t4d

**Comment by YxRicardo** [comment]
Thank you so much for the help. Really appreciate that.
